// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsR_Hfa3PZHH27TJj3RtO9zwV9dQpkck0',
    appId: '1:798721791100:web:cdc4607dc67660da1625f9',
    messagingSenderId: '798721791100',
    projectId: 'echo-news-prashant',
    authDomain: 'echo-news-prashant.firebaseapp.com',
    storageBucket: 'echo-news-prashant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIVEu3TMDK9TOfSWYTLTGhW2d3l1HrMig',
    appId: '1:798721791100:android:4bf19c7cb6fe1d9a1625f9',
    messagingSenderId: '798721791100',
    projectId: 'echo-news-prashant',
    storageBucket: 'echo-news-prashant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vo2iiyYw7YCv92aOCjsgvdDc2vf5BTk',
    appId: '1:798721791100:ios:2b26ae8f9ef4ec9f1625f9',
    messagingSenderId: '798721791100',
    projectId: 'echo-news-prashant',
    storageBucket: 'echo-news-prashant.firebasestorage.app',
    iosBundleId: 'com.prashant.echonews.echoNews',
  );
}
